### ISSUE TITLE
Selected rows erros

### ISSUE THREAD

**Issue by dlape** [Sridatta19/react-listbox#2]
after clicking the rows this is what happens, is this bug , error or I just carelessly forgot something.
![image](https://user-images.githubusercontent.com/29973629/31528321-2de57bb4-b005-11e7-9770-2667d02e58d4.jpg)

**Comment by Sridatta19** [comment]
@dlape this could've been due to the overriding css classes. Try to inspect in dev tools and you might figure out the cause

**Comment by dlape** [comment]
Yeah, I create a dummy project and it works as expected I just need to find out wheres the error happens. And one thing I tried using dynamic data from my server but it always gives me this error: 

> Cannot read property 'toLowerCase' of undefined.

but I didnt use toLowerCase method. What do you think is the cause for this sir?.

**Comment by Sridatta19** [comment]
You could be passing undefined values to the listbox. Could you share a piece of code so that I can take a better look at it?
