### ISSUE TITLE
Select values is not working

### ISSUE THREAD

**Issue by XXChester** [Sridatta19/react-listbox#6]
I am trying to on page load automatically have some values selected (shown in the right pane). I have confirmed in the libraries componentWillReceiveProps that it is receiving the correct values, yet nothing is being selected.

Any suggestions?

I added a "getting selected" and "getting options" debug statements in the componentWillReceiveProps method and this is the output (shortened for readability):
```
getting options: [{"value":24,"label":"Residential"},{"value":25,"label":"Commercial"}]
getting selected: [25,24]
```
As shown the types match (integers) and the values match, so why does it not select them?

Thanks.

**Comment by Sridatta19** [comment]
I believe issue is fixed in 1.2.10
