### ISSUE TITLE
Unable to Use ListBox

### ISSUE THREAD

**Issue by askshinde** [Sridatta19/react-listbox#9]
react-dom.development.js?61bb:88 Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
    in DoubleListBox

Above error message I am receiving when using ListBox

options={this.state.teachers} defined inside constructor class

**Comment by Sridatta19** [comment]
Hi @askshinde,

Can you provide more information so that I can investigate the issue further? A codesandbox also can help.

Thanks,
Sridatta

**Comment by askshinde** [comment]
Thanks for the response I managed to do with my self component
